apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: gzctf-config
    namespace: gzctf-server
    files:
      - appsettings.json
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: gzctf-secrets
    namespace: gzctf-server
    envs:
      - ./env/.env
    options:
      disableNameSuffixHash: true

resources:
  - ./roles.yaml
