apiVersion: v1
kind: PersistentVolume
metadata:
  name: gzctf-files-pv
  namespace: gzctf-server
  annotations:
    pv.kubernetes.io/provisioned-by: local-path
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain # We do not need this actually, files will be there even if pv is deleted
  hostPath:
    path: /mnt/data/gzctf/files # local path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gzctf-db-pv
  namespace: gzctf-server
  annotations:
    pv.kubernetes.io/provisioned-by: local-path
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain # We do not need this actually, files will be there even if pv is deleted
  hostPath:
    path: /mnt/data/gzctf/db # local path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gzctf-files
  namespace: gzctf-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: gzctf-files-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gzctf-db
  namespace: gzctf-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: gzctf-db-pv
